language: elixir
elixir: '1.7.4'
otp_release: '21.0'

cache:
  directories:
    - _build
    - deps

env:
  global:
    - MIX_ENV=test
    - DATABASE_URL=postgres://postgres@localhost:5432/travis_ci_test

addons:
  postgresql: 9.6

before_script:
  - mix ecto.setup
